site_name: Chaucha Docs
pages:
    - Inicio: index.md
    - Aportes de la comunidad:
      - Introducci√≥n: intro.md
      - Como minar Chauchas: mining.md
      - Tips de seguridad: sec.md
      - HODL !: hodl.md
    - Chaucha:
      - Whitepaper: whitepaper.md
    - Testimonios:
      - La Chaucha y los dibujos: leo.md
theme:
  name: 'material'
  font:
    text: 'Montserrat'
    code: 'Space Mono'
  palette:
    primary: 'white'
    accent: 'pink'
  logo: 'img/chaucha.svg'

  favicon: 'img/favicon.ico'
  language: 'es'

repo_name: 'proyecto-chaucha/docs'
repo_url: 'https://github.com/proyecto-chaucha/docs'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/proyecto-chaucha'
    - type: 'facebook'
      link: 'https://facebook.com/proyectochaucha'
    - type: 'telegram'
      link: 'https://t.me/chaucha'
  search:
    language: 'en, es'